NoScript: JavaScript wird benötigt
Password: Passwort
PasswordRepeat: Wiederholen
Activate: Aktivieren
Days: Tage
LoggedInAs: Eingeloggt als
Logout: Logout
New: Neu
Top: Top
Directory: Verzeichnis
NewTorrents: Neue Torrents
TopTorrents: Beliebte Torrents
TopDownloadedDay: Meist heruntergeladen an 1 Tag
TopDownloadedDays n@Int: Meist heruntergeladen in #{show n} Tagen
TopDownloadedAll: Meist heruntergeladen jeher
In: bei
By: von
FrontAbout: Bitlove ist das Rundumsorglospaket für Podcast-Downloads mit P2P-Geschwindigkeit. Für alle Mediendateien im RSS-Feed erstellen wir einen Torrent, um die Daten auch mit anderen Herunterladenden zu teilen. Ein eigener Seeder sorgt dabei für garantierte Verteilung und Mindestgeschwindigkeit.
LearnMore: Erfahre mehr…
AreYouPublisher: Bist Du ein Podcast Publisher?
SignUp: Anmelden
Login: Login
Private: Privat
PrivateExplain: Privat — Nicht im Verzeichnis aufgeführt.
ErrorExplain: Momentan bleibt der Fehlerstatus bei HTTP 304 Not modified erhalten. Das ist nicht weiter schlimm wenn die Torrents stimmen.
EnclosureErrors: Enclosure-Fehler
DownloadTorrent name@Text: #{name} mit BitTorrent herunterladen
DownloadSize: Downloadgröße
TitleNew: Bitlove: Neue Torrents
TitleTop: Bitlove: Beliebte Torrents
TitleTopDownloaded: Bitlove: Meist heruntergeladen
TitleUser user@Text: #{user} auf Bitlove
TitleFeed title@Text: #{title} bei Bitlove
TitleSignup: Bitlove: Anmeldung
TitleError: Fehler
TitleReactivate: Bitlove: Passwortwiederherstellung
TitleDirectory: Bitlove: Verzeichnis
HeadingDirectory: Verzeichnis torrentifizierter Podcaster
