NoScript: JavaScript wird benötigt
Password: Passwort
PasswordRepeat: Wiederholen
Activate: Aktivieren
Within: Innerhalb
Days: Tage
LoggedInAs: Eingeloggt als
Logout: Logout
Front: Was ist Bitlove?
New: Neue Folgen
Top: Top-Folgen
Directory: Alle Folgen
GettingStarted: Kurzanleitung
NewTorrents: Neue Torrents
TopTorrents: Beliebte Torrents
TopDownloadedDay: Meist heruntergeladen an einem Tag
TopDownloadedDays n@Int: Meist heruntergeladen in #{show n} Tagen
TopDownloadedAll: Meist heruntergeladen jeher
In: bei
By: von
FrontAbout: Bitlove ist das Rundumsorglospaket für Podcast-Downloads mit P2P-Geschwindigkeit. Für alle Mediendateien im RSS-Feed erstellen wir einen Torrent, um die Daten auch mit anderen Herunterladenden zu teilen. Ein eigener Seeder sorgt dabei für garantierte Verteilung und Mindestgeschwindigkeit.
LearnMore: Erfahre mehr…
AreYouPublisher: Bist Du ein Podcast Publisher?
SignUp: Anmelden
Login: Login
MyFeeds: Meine Feeds
Search: Suchen
Private: Privat
PrivateExplain: Privat — Nicht im Verzeichnis aufgeführt.
ErrorExplain: Momentan bleibt der Fehlerstatus bei HTTP 304 Not modified erhalten. Das ist nicht weiter schlimm wenn die Torrents stimmen.
EnclosureErrors: Enclosure-Fehler
DownloadTorrent name@Text: #{name} mit BitTorrent herunterladen
DownloadSize: Downloadgröße
TitleNew: Bitlove: Neue Torrents
TitleTop: Bitlove: Beliebte Torrents
TitleTopDownloaded: Bitlove: Meist heruntergeladen
TitleUser user@Text: #{user} auf Bitlove
TitleFeed title@Text: #{title} bei Bitlove
TitleSignup: Bitlove: Anmeldung
TitleError: Fehler
TitleReactivate: Bitlove: Passwortwiederherstellung
TitleDirectory: Bitlove: Verzeichnis
HeadingDirectory: Verzeichnis torrentifizierter Podcaster
TitleHelp: Bitlove: Hilfe
HeadingSignup: Podcaster-Anmeldung
Username: Benutzername
UsernameHint: Dein Benutzername ist dein Label. Es wird überall sichtbar sein und kann mehrere Feeds beinhalten.
Email: E-Mail
EmailHint: Wir schicken eine Aktivierungsmail um die Anmeldung zu bestätigen.
Tos1: Die Medien die ich hier veröffentliche dürfen frei kopiert werden.
Tos2: Ich werde diesen Dienst ausschließlich für Inhalte nutzen die (weiter-)verbreitet werden dürfen.
NoWarez: Keine warez
NoWarezExplanation: Alle Podcast-Feeds und -Daten kommen von normalen Web-Servern. Hol dir eine Seedbox!
Broadcaster: Vertreter einer Sendeanstalt?
BroadcasterExplanation: Veröffentlichen Sie ihre Inhalte auf Bitlove und machen damit Ihr Publikum froh! Kontaktieren Sie
ForgotPasswordQuestion: Passwort vergessen?
Reactivate: Benutzer reaktivieren
Ok: Okay