NoScript: JavaScript wird benötigt
Password: Passwort
PasswordRepeat: Wiederholen
Activate: Aktivieren
Within: Innerhalb
Days: Tage
LoggedInAs: Eingeloggt als
Logout: Logout
Front: Über Bitlove
New: Neue Folgen
Top: Top-Folgen
For: Für
Users: Nutzer
Podcasters: Podcaster
Directory: Verzeichnis
GettingStarted: Kurzanleitung
NewTorrents: Neue Torrents
TopTorrents: Beliebte Torrents
TopDownloadedDay: Meist heruntergeladen an einem Tag
TopDownloadedDays n@Int: Meist heruntergeladen in #{show n} Tagen
TopDownloadedAll: Meist heruntergeladen jeher
SearchHeading needle@Text: Suche nach: #{needle}
In: bei
By: von
FrontAbout: Bitlove erstellt für alle Mediendateien eines RSS-Feeds Torrents und ist zugleich Seeder
FrontUserH: Was heißt das für Nutzer?
FrontUser1a: High-speed Downloads von
FrontUser1b: vielen Peers
FrontUser2a: Datenintegrität mit
FrontUser2b: SHA1-Hashes
FrontUser3a: Feeds für
FrontUser3b: automatische Abonnements
FrontUser4a: Viele Podcasts auf
FrontUser4b: einen Blick
FrontPodcasterH: …und für Podcaster?
FrontPodcaster1a: Unterstütze
FrontPodcaster1b: P2P-Technologie!
FrontPodcaster2a: Spare Bandbreite durch
FrontPodcaster2b: viele Seeder
FrontPodcaster3a: Umso mehr Downloader,
FrontPodcaster3b: desto schneller
FrontPodcaster4a: Werde im
FrontPodcaster4b: Verzeichnis gefunden
LearnMore: Erfahre mehr…
AreYouPublisher: Bist Du ein Podcast Publisher?
SignUp: Anmelden
Login: Login
MyFeeds: Meine Feeds
Search: Suchen
NothingFound: Nichts gefunden
Private: Privat
PrivateExplain: Privat — Nicht im Verzeichnis aufgeführt.
ErrorExplain: Momentan bleibt der Fehlerstatus bei HTTP 304 Not modified erhalten. Das ist nicht weiter schlimm wenn die Torrents stimmen.
EnclosureErrors: Enclosure-Fehler
DownloadTorrent name@Text: #{name} mit BitTorrent herunterladen
DownloadSize: Downloadgröße
TitleNew: Bitlove: Neue Torrents
TitleTop: Bitlove: Beliebte Torrents
TitleTopDownloaded: Bitlove: Meist heruntergeladen
TitleUser user@Text: #{user} auf Bitlove
TitleFeed title@Text: #{title} bei Bitlove
TitleSignup: Bitlove: Anmeldung
TitleError: Fehler
TitleReactivate: Bitlove: Passwortwiederherstellung
TitleDirectory: Bitlove: Verzeichnis
TitleSearch needle@Text: Bitlove: Suche nach #{needle}
HeadingDirectory: Verzeichnis torrentifizierter Podcaster
TitleHelp: Bitlove: Hilfe
HeadingSignup: Podcaster-Anmeldung
Username: Benutzername
UsernameHint: Dein Benutzername ist dein Label. Es wird überall sichtbar sein und kann mehrere Feeds beinhalten.
Email: E-Mail
EmailHint: Wir schicken eine Aktivierungsmail um die Anmeldung zu bestätigen.
Tos1: Die Medien die ich hier veröffentliche dürfen frei kopiert werden.
Tos2: Ich werde diesen Dienst ausschließlich für Inhalte nutzen die (weiter-)verbreitet werden dürfen.
NoWarez: Keine warez
NoWarezExplanation: Alle Podcast-Feeds und -Daten kommen von normalen Web-Servern. Hol dir eine Seedbox!
Broadcaster: Vertreter einer Sendeanstalt?
BroadcasterExplanation: Veröffentlichen Sie ihre Inhalte auf Bitlove und machen damit Ihr Publikum froh! Kontaktieren Sie
ForgotPasswordQuestion: Passwort vergessen?
Reactivate: Benutzer reaktivieren
Ok: Okay