NoScript: JavaScript is mandatory beyond this point
Password: Password
PasswordRepeat: Repeat
Activate: Activate
Days: days
LoggedInAs: Logged in as
Logout: Logout
New: New
Top: Top
Directory: Directory
NewTorrents: New Torrents
TopTorrents: Popular Torrents
TopDownloadedDay: Top downloaded in 1 day
TopDownloadedDays n@Int: Top downloaded in #{show n} days
TopDownloadedAll: Top downloaded all time
In: in
By: by
