NoScript: JavaScript is mandatory beyond this point
Password: Password
PasswordRepeat: Repeat
Activate: Activate
Days: days
LoggedInAs: Logged in as
Logout: Logout
New: New
Top: Top
Directory: Directory
NewTorrents: New Torrents
TopTorrents: Popular Torrents
TopDownloadedDay: Top downloaded in 1 day
TopDownloadedDays n@Int: Top downloaded in #{show n} days
TopDownloadedAll: Top downloaded all time
In: in
By: by
FrontAbout: Bitlove is the fully automatic Podcast download service on P2P speed. We generate a Torrent for all media files of an RSS feed and will seed them all the time.
LearnMore: Learn more…
AreYouPublisher: Are You a Podcast Publisher?
SignUp: Sign up
Login: Login
Private: Private
PrivateExplain: Private — Not included in directory or public torrent listings
ErrorExplain: Right now, the error message will not be cleared in case of HTTP 304 Not modified. Don't worry too much if your torrents appear to be fine.
EnclosureErrors: Enclosure Errors
DownloadTorrent name@Text: Download #{name} with BitTorrent
DownloadSize: Download size
Title: Bitlove: Peer-to-Peer Love for Your Podcast Downloads
TitleNew: Bitlove: New Torrents
TitleTop: Bitlove: Popular Torrents
TitleTopDownloaded: Bitlove: Top Downloaded
TitleUser user@Text: #{user} on Bitlove
TitleFeed title@Text: #{title} on Bitlove
TitleSignup: Bitlove: Signup
TitleError: Error
TitleReactivate: Bitlove: Recover your password
TitleDirectory: Bitlove: Directory
HeadingDirectory: Directory of torrentified Podcasters
TitleHelp: Bitlove: Help
HeadingSignup: Podcaster Signup
Username: Username
UsernameHint: Your username is your label. It will be visible everywhere, and you can put multiple feeds under it. Give it some thought.
Email: Email
EmailHint: We will send a password activation EMail for completing signup.
Tos1: The media I am about to publish here is free to copy.
Tos2: I will use this service only for content I am allowed to (re-)distribute.
NoWarez: No warez
NoWarezExplanation: All podcast feeds and torrents are backed by actual Web servers. Get your own seedbox.
Broadcaster: Representing a broadcast institution?
BroadcasterExplanation: Place your content on Bitlove to make your audience happy! Contact us at
ForgotPasswordQuestion: Forgot password?
Reactivate: Reactivate your account
Ok: Ok
