NoScript: JavaScript is mandatory beyond this point
Password: Password
PasswordRepeat: Repeat
Activate: Activate
Within: Within
Days: days
LoggedInAs: Logged in as
Logout: Logout
Front: About
New: New
Top: Top
For: For
Users: Users
Podcasters: Podcasters
GettingStarted: Getting started
Directory: Directory
DirectoryIndexBack: Back to directory index
NewTorrents: New Torrents
TopTorrents: Popular Torrents
TopDownloadedDay: Top downloaded in 1 day
TopDownloadedDays n@Int: Top downloaded in #{show n} days
TopDownloadedAll: Top downloaded all time
SearchHeading needle@Text: Search for: #{needle}
In: in
By: by
FrontAbout: Bitlove creates Torrents for all enclosures of an RSS/ATOM feed and seeds them
FrontUserH: What's in for users?
FrontUser1a: High-speed downloads from
FrontUser1b: many peers
FrontUser2a: Data integrity through
FrontUser2b: SHA1 hashes
FrontUser3a: Feeds for
FrontUser3b: automatic subscription
FrontUser4a: Many podcasts at
FrontUser4b: a glance
FrontPodcasterH: …and for Podcasters?
FrontPodcaster1a: Support
FrontPodcaster1b: P2P technology!
FrontPodcaster2a: Save bandwidth with
FrontPodcaster2b: many seeders
FrontPodcaster3a: The more downloaders
FrontPodcaster3b: the more throughput
FrontPodcaster4a: Get discovered in
FrontPodcaster4b: our directory
LearnMore: Learn more…
AreYouPublisher: Are You a Podcast Publisher?
SignUp: Sign up
Login: Login
MyFeeds: My feeds
Search: Search
NothingFound: Nothing found
Private: Private
PrivateExplain: Private — Not included in directory or public torrent listings
ErrorExplain: Right now, the error message will not be cleared in case of HTTP 304 Not modified. Don't worry too much if your torrents appear to be fine.
EnclosureErrors: Enclosure Errors
DownloadTorrent name@Text: Download #{name} with BitTorrent
DownloadSize: Download size
Title: Bitlove: Peer-to-Peer Love for Your Podcast Downloads
TitleNew: Bitlove: New Torrents
TitleTop: Bitlove: Popular Torrents
TitleTopDownloaded: Bitlove: Top Downloaded
TitleUser user@Text: #{user} on Bitlove
TitleFeed title@Text: #{title} on Bitlove
TitleSignup: Bitlove: Signup
TitleError: Error
TitleReactivate: Bitlove: Recover your password
TitleDirectory: Bitlove: Directory
TitleSearch needle@Text: Bitlove: Search for #{needle}
HeadingDirectory: Directory of torrentified Podcasters
TitleHelp: Bitlove: Help
HeadingSignup: Podcaster Signup
Username: Username
UsernameHint: Your username is your label. It will be visible everywhere, and you can put multiple feeds under it. Give it some thought.
Email: Email
EmailHint: We will send a password activation EMail for completing signup.
Tos1: The media I am about to publish here is free to copy.
Tos2: I will use this service only for content I am allowed to (re-)distribute.
NoWarez: No warez
NoWarezExplanation: All podcast feeds and torrents are backed by actual Web servers. Get your own seedbox.
Broadcaster: Representing a broadcast institution?
BroadcasterExplanation: Place your content on Bitlove to make your audience happy! Contact us at
ForgotPasswordQuestion: Forgot password?
Reactivate: Reactivate your account
Ok: Ok
Recommend1: We recommend
Recommend2: for streaming playback
