Default: &defaults
  host: "*6"
  port: 8081
  approot: ""
  copyright: APL2
  served_vhosts:
    - bitlove.org
    - api.bitlove.org
  tracker_urls:
    - http://t.bitlove.org/announce
    - wss://t.bitlove.org/webtorrent-announce
  contact_mail: "mail@bitlove.org"
  export_auth:
    - "test:test"
    - "bigtelco:i-am-evil"

Development:
  approot: "http://localhost:8081"
  served_vhosts:
    - localhost
    - bitlove.org
    - api.bitlove.org
  tracker_urls:
    - http://localhost:8081/announce
    - ws://localhost:8081/webtorrent-announce
  <<: *defaults

Production4:
  host: "*4"
  port: 80
  approot: "http://bitlove.org"
  <<: *defaults

Production4SSL:
  host: "*4"
  port: 443
  approot: "https://bitlove.org"
  cert: "bitlove_ca.pem"
  key: "bitlove_privatekey.rsa"
  <<: *defaults

Production6:
  host: "*6"
  port: 80
  approot: "http://bitlove.org"
  <<: *defaults

Production6SSL:
  host: "*6"
  port: 443
  approot: "https://bitlove.org"
  cert: "bitlove_ca.pem"
  key: "bitlove_privatekey.rsa"
  <<: *defaults
